- hosts: all
  sudo: True
  tasks:
    - name: create volume
      lvol: vg=gfsm lv={{ volname }} size={{ volsize }}

    - name: format volume
      filesystem: fstype=xfs dev=/dev/gfsm/{{ volname }}

    - name: create /gluster
      file: path=/gluster state=directory mode=0755

    - name: create mount point
      file: path=/gluster/{{ volname }} state=directory mode=0755

    - name: mount volume
      mount: name=/gluster/{{ volname }} src=/dev/gfsm/{{ volname }} opts=noatime,nodiratime,inode64 state=mounted fstype=xfs

    - name: make brick
      file: path=/gluster/{{ volname }}/brick state=directory mode=0755

    - name: gluster peer
      command: gluster peer probe {{ item }}
      with_items: groups.gluster_server
      when: inventory_hostname == groups.gluster_server[0]

    - name: Create default volume
      shell: >
             {% set bricks = "" %}
             {% for item in groups.gluster_server %}
             {%  set bricks = bricks ~ " " ~ item ~ ":/gluster/" ~ volname ~ "/brick" %}
                {% if loop.last %}
                 gluster volume info {{ volname }} || 
                 gluster volume create {{ volname }} replica {{ replica }} {{ bricks }}
                {% endif %}
             {% endfor %} 
      when: inventory_hostname == groups.gluster_server[0]
